[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 155 65535 0 0][uf 3 1 1 0 0 4 0 0]Huh? Junpei-kun and Ryoji-kun are lying on the ground over there.[n][uf 1 1][e]

[msg MSG_001_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 155 65535 0 0][uf 3 1 1 0 0 5 0 0]Their faces are all red. Are they okay?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 155 65535 0 0][uf 3 1 1 0 0 6 0 0]I bet they were doing something stupid again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 155 65535 0 0][uf 3 1 1 0 0 7 0 0]Just leave 'em alone.[n][uf 1 1][e]