[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]Wow! This hot spring is huge![n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 154 65535 0 0][uf 4 23 0 1 1 25 25]Wow, you're right. It's as big as a swimming pool.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 4 23 0 1 0 25 25]So this is an outdoor hot spring. Unfortunately, its therapeutic benefits have no effect on me.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]......?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I hear splashing from the hot spring...[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 154 65535 0 0][uf 4 23 0 1 2 25 25]...Who's that!? Is someone there!?[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 65535 0 0][uf 4 23 0 1 0 25 25]What's wrong, Yukari? Did you hear something?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]Did you... hear that just now?[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Hear what...?[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 154 65535 0 0][uf 4 23 0 1 0 25 25]What about you, [uf 4 2]-chan? Did you hear something...?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]I heard it too![e]
[uf 0 5 65278][uf 2 1]It's your imagination.[e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]...You did, huh?[n][uf 1 1][e]

[msg MSG_010_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]Fuuka, could you check over there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]I-It could be a ghost... [n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 154 65535 0 0][uf 4 23 0 1 2 25 25]I-I'm not joking![n][uf 1 1][e]

[msg MSG_011_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]Fuuka, could you check over there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]I-It could be a ghost...[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 154 65535 0 0][uf 4 23 0 1 0 25 25]Um... O-Okay...[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]It's been decided that we're all going to find out what the sounds from the hot spring were...[n][uf 1 1][e]
