[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Okay, I'll go around from the left.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 0 25 25]O-Okay. Then I'll head right...[n][uf 1 1][e]

[msg MSG_001_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Come with me, [uf 4 2]...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]Oh, wait! Could there be other guests in the bath, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]If that's the case, would we be causing trouble, walking around like this...?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah... Let's stop.[e]
[uf 0 5 65278][uf 2 1]Is someone here!?[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Y-Yeah, I'm with you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]C'mon, guys, let's stop poking around and just enjoy the water![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I called out to the depths of the hot spring...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...There is no answer.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]I-I guess not...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 3 25 25]Was it really a ghost...? Haha, who am I kidding?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 154 65535 0 0][uf 4 23 0 1 3 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Hmm... I don't see anything particularly suspicious...[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Let’s check the hot-water supply.[e]
[uf 0 5 65278][uf 2 1]Let’s check the floating leaves.[e]
[uf 0 5 65278][uf 2 1]We should give up.[e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]We checked near the hot-water supply area...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...But all we find there is hot water streaming out.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Nothing here...[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]We checked near where the maple leaves are floating...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...But all we find there are the maple leaves.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Nothing here...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Yeah, you're right...[n][uf 1 1][e]

[msg MSG_012_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]C'mon, guys, let's stop poking around and just enjoy the water![n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 0 25 25]I-I'm not scared, you know?[n][uf 1 1][e]

[msg MSG_013_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 154 65535 0 0][uf 4 23 0 1 2 25 25]......![n][uf 1 1][e]

[msg MSG_013_2_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 154 65535 0 0][uf 4 23 0 1 2 25 25]Wh-What was that? An animal?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]A monkey, maybe?[e]
[uf 0 5 65278][uf 2 1]A ghost, maybe...?[e]
[uf 0 5 65278][uf 2 1]A person, maybe?[e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]Ooh! Like on TV![n][uf 1 1][e]

[msg MSG_015_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]Whew... Just a monkey, huh? Well, I'm scared enough... I'll leave it be.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 154 65535 0 0][uf 4 23 0 1 2 25 25]I told you not to say that![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 154 65535 0 0][uf 4 23 0 1 2 25 25]If you say stuff like that, it'll really come true![n][uf 1 1][e]

[msg MSG_016_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]C'mon, let's get out! It's getting hot. ...I said, it's getting hot![n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]But no one answered when I called out a second ago.[n][uf 1 1][e]

[msg MSG_017_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 0 25 25]Maybe I was just hearing things... Should we go check up on Fuuka?[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Let's do that.[e]
[uf 0 5 65278][uf 2 1]Let's check ahead first.[e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Fuuka! Did you find anything?[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 154 65535 0 0][uf 4 23 0 1 0 25 25]No, there's nothing over here either.[n][uf 1 1][e]
[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 154 65535 0 0][uf 4 23 0 1 1 25 25]Oh... Well, let's stop poking around and just enjoy the water, then.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]Wh-Why, is there someplace over there that seems suspicious?[n][uf 1 1][e]

[sel SEL_023_0_0 top]
[uf 0 5 65278][uf 2 1]Under the water![e]
[uf 0 5 65278][uf 2 1]The hollow in that rock![e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 154 65535 0 0][uf 4 23 0 1 3 25 25]Down there!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 154 65535 0 0][uf 4 23 0 1 3 25 25]Yikes, I'm getting this sudden image of, like... a dozen hands suddenly reaching out of the hot water![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 154 65535 0 0][uf 4 23 0 1 3 25 25]......[n][uf 1 1][e]

[msg MSG_024_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]C'mon, let's get out! It's getting hot. ...I said, it's getting hot![n][uf 1 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]Really...? I was kinda deliberately avoiding that area...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]It feels like something might jump out...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]Wait a sec... Wouldn't that mean a person could hide there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 154 65535 0 0][uf 4 23 0 1 0 25 25]......[n][uf 1 1][e]

[msg MSG_025_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 154 65535 0 0][uf 4 23 0 1 2 25 25]Let's check it out![n][uf 1 1][e]